name: Hello World

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3   # أو v4 أو v5 لو متاح
      - name: Echo text
        run: echo "Hello, world!"
