name: Hello World

on:
  push:   

jobs:
  - name: checkout Repo
    uses: actions/checkout@v5 
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: echo "Hello, world!"
